id: da7bc5e67f8c45cc87be391515899bcd
initial_creation_type: ocr
source_metadata:
  volumes:
    f7651f3717a34a36b6a9006652b0b2b8:
      base_file: v025.txt
      image_group_id: I1PD95870
      title: ཕྱག་ན་རྡོ་རྗེའི་ལམ་ཡན་ལག་བརྒྱད་པ།
      total_pages: 1853
      volume_number: 25
